"""coda email e promemoria

Revision ID: 0cb722c2328f
Revises: 30c581d8709f
Create Date: 2026-08-05 14:24:03.207236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb722c2328f'
down_revision = '30c581d8709f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('text_body', sa.Text(), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('related_type', sa.String(length=50), nullable=False),
    sa.Column('related_id', sa.String(length=80), nullable=False),
    sa.Column('unique_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_outbox')),
    sa.UniqueConstraint('unique_key', name=op.f('uq_email_outbox_unique_key'))
    )
    with op.batch_alter_table('email_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_outbox_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_outbox_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_outbox_recipient_email'), ['recipient_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_outbox_status'), ['status'], unique=False)

    op.create_table('notification_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_reminders_enabled', sa.Boolean(), nullable=False),
    sa.Column('course_reminder_days', sa.Integer(), nullable=False),
    sa.Column('certificate_reminders_enabled', sa.Boolean(), nullable=False),
    sa.Column('certificate_expiry_days', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_notification_configurations_updated_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_configurations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_configurations')
    with op.batch_alter_table('email_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_outbox_status'))
        batch_op.drop_index(batch_op.f('ix_email_outbox_recipient_email'))
        batch_op.drop_index(batch_op.f('ix_email_outbox_next_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_email_outbox_message_type'))

    op.drop_table('email_outbox')
    # ### end Alembic commands ###
