"""portale aziende e associazione attestati

Revision ID: 30c581d8709f
Revises: 569d6516af33
Create Date: 2026-08-05 14:20:42.122986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c581d8709f'
down_revision = '569d6516af33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_contacts_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_company_contacts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_contacts')),
    sa.UniqueConstraint('company_id', 'user_id', name='uq_company_contact_user')
    )
    with op.batch_alter_table('company_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_contacts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_contacts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_certificates_company_id'), ['company_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_certificates_company_id_companies'), 'companies', ['company_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('one_time_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('one_time_codes', schema=None) as batch_op:
        batch_op.drop_column('context')

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_certificates_company_id_companies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_certificates_company_id'))
        batch_op.drop_column('company_id')

    with op.batch_alter_table('company_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_contacts_user_id'))
        batch_op.drop_index(batch_op.f('ix_company_contacts_company_id'))

    op.drop_table('company_contacts')
    # ### end Alembic commands ###
