"""token di accesso MCP

Revision ID: 4ac6f69887d4
Revises: 0cb722c2328f
Create Date: 2026-08-05 16:32:35.657920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac6f69887d4'
down_revision = '0cb722c2328f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_access_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('token_prefix', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_mcp_access_tokens_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_access_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_mcp_access_tokens_token_hash'))
    )
    with op.batch_alter_table('mcp_access_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_access_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_access_tokens_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_access_tokens_token_prefix'), ['token_prefix'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_access_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_access_tokens_token_prefix'))
        batch_op.drop_index(batch_op.f('ix_mcp_access_tokens_is_active'))
        batch_op.drop_index(batch_op.f('ix_mcp_access_tokens_expires_at'))

    op.drop_table('mcp_access_tokens')
    # ### end Alembic commands ###
