"""versione applicazione e database

Revision ID: 707b9cfc0a06
Revises: 4ac6f69887d4
Create Date: 2026-08-05 17:20:47.391156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707b9cfc0a06'
down_revision = '4ac6f69887d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_version', sa.String(length=32), nullable=False),
    sa.Column('database_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_version'))
    )
    op.execute(sa.text(
        "INSERT INTO system_version "
        "(id, application_version, database_version, updated_at) "
        "VALUES (1, '0.1.0', 1, CURRENT_TIMESTAMP)"
    ))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_version')
    # ### end Alembic commands ###
