"""documenti modelli firme e attestati

Revision ID: 73391b7d4a79
Revises: f857cf966ce1
Create Date: 2026-08-05 14:07:29.156711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73391b7d4a79'
down_revision = 'f857cf966ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('stored_file_id', sa.String(length=36), nullable=False),
    sa.Column('placeholders', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stored_file_id'], ['stored_files.id'], name=op.f('fk_certificate_templates_stored_file_id_stored_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_certificate_templates_uploaded_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificate_templates')),
    sa.UniqueConstraint('stored_file_id', name=op.f('uq_certificate_templates_stored_file_id'))
    )
    with op.batch_alter_table('certificate_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_templates_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_templates_name'), ['name'], unique=False)

    op.create_table('signature_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('signer_name', sa.String(length=160), nullable=False),
    sa.Column('signer_title', sa.String(length=160), nullable=False),
    sa.Column('stored_file_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stored_file_id'], ['stored_files.id'], name=op.f('fk_signature_assets_stored_file_id_stored_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_signature_assets_uploaded_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signature_assets')),
    sa.UniqueConstraint('stored_file_id', name=op.f('uq_signature_assets_stored_file_id'))
    )
    with op.batch_alter_table('signature_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signature_assets_is_active'), ['is_active'], unique=False)

    op.create_table('certificates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=True),
    sa.Column('participant_user_id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=True),
    sa.Column('pdf_file_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('certificate_number', sa.String(length=80), nullable=True),
    sa.Column('title_snapshot', sa.String(length=240), nullable=False),
    sa.Column('course_date', sa.Date(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=False),
    sa.Column('generated_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_certificates_course_id_courses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_certificates_enrollment_id_enrollments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], name=op.f('fk_certificates_generated_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['participant_user_id'], ['users.id'], name=op.f('fk_certificates_participant_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pdf_file_id'], ['stored_files.id'], name=op.f('fk_certificates_pdf_file_id_stored_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['certificate_templates.id'], name=op.f('fk_certificates_template_id_certificate_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates')),
    sa.UniqueConstraint('enrollment_id', name=op.f('uq_certificates_enrollment_id')),
    sa.UniqueConstraint('pdf_file_id', name=op.f('uq_certificates_pdf_file_id'))
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_certificate_number'), ['certificate_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_certificates_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_participant_user_id'), ['participant_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_verification_status'), ['verification_status'], unique=False)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_template_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('signature_asset_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_courses_signature_asset_id_signature_assets'), 'signature_assets', ['signature_asset_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_courses_certificate_template_id_certificate_templates'), 'certificate_templates', ['certificate_template_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_courses_certificate_template_id_certificate_templates'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_courses_signature_asset_id_signature_assets'), type_='foreignkey')
        batch_op.drop_column('signature_asset_id')
        batch_op.drop_column('certificate_template_id')

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_verification_status'))
        batch_op.drop_index(batch_op.f('ix_certificates_status'))
        batch_op.drop_index(batch_op.f('ix_certificates_source'))
        batch_op.drop_index(batch_op.f('ix_certificates_participant_user_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_expires_at'))
        batch_op.drop_index(batch_op.f('ix_certificates_course_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_certificate_number'))

    op.drop_table('certificates')
    with op.batch_alter_table('signature_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signature_assets_is_active'))

    op.drop_table('signature_assets')
    with op.batch_alter_table('certificate_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_templates_name'))
        batch_op.drop_index(batch_op.f('ix_certificate_templates_is_active'))

    op.drop_table('certificate_templates')
    # ### end Alembic commands ###
