"""aziende partecipanti corsi e ammissioni

Revision ID: 9374ded5abf9
Revises: b8857511739f
Create Date: 2026-08-05 13:05:39.582318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9374ded5abf9'
down_revision = 'b8857511739f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_name', sa.String(length=240), nullable=False),
    sa.Column('vat_number', sa.String(length=32), nullable=False),
    sa.Column('tax_code', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=240), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('province', sa.String(length=8), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('pec', sa.String(length=320), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_business_name'), ['business_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_vat_number'), ['vat_number'], unique=True)

    op.create_table('courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creator_user_id', sa.String(length=36), nullable=False),
    sa.Column('referent_user_id', sa.String(length=36), nullable=False),
    sa.Column('delivery_mode', sa.String(length=20), nullable=False),
    sa.Column('meeting_url', sa.String(length=500), nullable=False),
    sa.Column('timezone_name', sa.String(length=64), nullable=False),
    sa.Column('certificate_validity_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], name=op.f('fk_courses_creator_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['referent_user_id'], ['users.id'], name=op.f('fk_courses_referent_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_courses_referent_user_id'), ['referent_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_title'), ['title'], unique=False)

    op.create_table('participant_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('birth_place', sa.String(length=160), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('tax_code', sa.String(length=32), nullable=False),
    sa.Column('certificate_title', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_participant_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_participant_profiles'))
    )
    op.create_table('stored_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=160), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_stored_files_uploaded_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stored_files')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_stored_files_storage_key'))
    )
    with op.batch_alter_table('stored_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stored_files_sha256'), ['sha256'], unique=False)

    op.create_table('admission_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('participant_user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('participant_message', sa.Text(), nullable=False),
    sa.Column('internal_note', sa.Text(), nullable=False),
    sa.Column('decision_message', sa.Text(), nullable=False),
    sa.Column('decided_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_admission_requests_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], name=op.f('fk_admission_requests_decided_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['participant_user_id'], ['users.id'], name=op.f('fk_admission_requests_participant_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admission_requests')),
    sa.UniqueConstraint('course_id', 'participant_user_id', name='uq_course_admission_participant')
    )
    with op.batch_alter_table('admission_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admission_requests_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_requests_participant_user_id'), ['participant_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_requests_status'), ['status'], unique=False)

    op.create_table('course_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('stored_file_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_documents_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stored_file_id'], ['stored_files.id'], name=op.f('fk_course_documents_stored_file_id_stored_files'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_documents')),
    sa.UniqueConstraint('course_id', 'stored_file_id', name='uq_course_document_file')
    )
    with op.batch_alter_table('course_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_documents_course_id'), ['course_id'], unique=False)

    op.create_table('course_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_sessions_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_sessions')),
    sa.UniqueConstraint('course_id', 'sequence', name='uq_course_session_sequence')
    )
    with op.batch_alter_table('course_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_sessions_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_sessions_starts_at'), ['starts_at'], unique=False)

    op.create_table('employments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('participant_user_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=False),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_employments_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['participant_user_id'], ['participant_profiles.user_id'], name=op.f('fk_employments_participant_user_id_participant_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employments')),
    sa.UniqueConstraint('participant_user_id', 'company_id', 'started_on', name='uq_employment_period')
    )
    with op.batch_alter_table('employments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employments_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employments_participant_user_id'), ['participant_user_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('participant_user_id', sa.String(length=36), nullable=False),
    sa.Column('admission_request_id', sa.String(length=36), nullable=True),
    sa.Column('attendance_status', sa.String(length=20), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admission_request_id'], ['admission_requests.id'], name=op.f('fk_enrollments_admission_request_id_admission_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_enrollments_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_user_id'], ['users.id'], name=op.f('fk_enrollments_participant_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('admission_request_id', name=op.f('uq_enrollments_admission_request_id')),
    sa.UniqueConstraint('course_id', 'participant_user_id', name='uq_course_enrollment_participant')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_participant_user_id'), ['participant_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_participant_user_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_course_id'))

    op.drop_table('enrollments')
    with op.batch_alter_table('employments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employments_participant_user_id'))
        batch_op.drop_index(batch_op.f('ix_employments_company_id'))

    op.drop_table('employments')
    with op.batch_alter_table('course_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_sessions_starts_at'))
        batch_op.drop_index(batch_op.f('ix_course_sessions_course_id'))

    op.drop_table('course_sessions')
    with op.batch_alter_table('course_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_documents_course_id'))

    op.drop_table('course_documents')
    with op.batch_alter_table('admission_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admission_requests_status'))
        batch_op.drop_index(batch_op.f('ix_admission_requests_participant_user_id'))
        batch_op.drop_index(batch_op.f('ix_admission_requests_course_id'))

    op.drop_table('admission_requests')
    with op.batch_alter_table('stored_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stored_files_sha256'))

    op.drop_table('stored_files')
    op.drop_table('participant_profiles')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_title'))
        batch_op.drop_index(batch_op.f('ix_courses_status'))
        batch_op.drop_index(batch_op.f('ix_courses_referent_user_id'))
        batch_op.drop_index(batch_op.f('ix_courses_code'))

    op.drop_table('courses')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_vat_number'))
        batch_op.drop_index(batch_op.f('ix_companies_business_name'))

    op.drop_table('companies')
    # ### end Alembic commands ###
