"""smtp otp e portale partecipanti

Revision ID: eeea76fdc860
Revises: 9374ded5abf9
Create Date: 2026-08-05 13:36:50.901987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeea76fdc860'
down_revision = '9374ded5abf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('one_time_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_one_time_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_one_time_codes'))
    )
    with op.batch_alter_table('one_time_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_one_time_codes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_one_time_codes_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_one_time_codes_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_one_time_codes_requested_ip'), ['requested_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_one_time_codes_user_id'), ['user_id'], unique=False)

    op.create_table('smtp_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=320), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('from_name', sa.String(length=160), nullable=False),
    sa.Column('use_starttls', sa.Boolean(), nullable=False),
    sa.Column('use_ssl', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_smtp_configurations_updated_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_smtp_configurations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smtp_configurations')
    with op.batch_alter_table('one_time_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_one_time_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_one_time_codes_requested_ip'))
        batch_op.drop_index(batch_op.f('ix_one_time_codes_purpose'))
        batch_op.drop_index(batch_op.f('ix_one_time_codes_expires_at'))
        batch_op.drop_index(batch_op.f('ix_one_time_codes_created_at'))

    op.drop_table('one_time_codes')
    # ### end Alembic commands ###
