"""questionari domande punteggi e tentativi

Revision ID: f857cf966ce1
Revises: eeea76fdc860
Create Date: 2026-08-05 13:52:54.914625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f857cf966ce1'
down_revision = 'eeea76fdc860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaires',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('passing_percentage', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_questionnaires_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by_user_id'], ['users.id'], name=op.f('fk_questionnaires_published_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questionnaires')),
    sa.UniqueConstraint('course_id', 'sort_order', name='uq_questionnaire_course_order')
    )
    with op.batch_alter_table('questionnaires', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questionnaires_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionnaires_is_published'), ['is_published'], unique=False)

    op.create_table('questionnaire_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('questionnaire_id', sa.String(length=36), nullable=False),
    sa.Column('participant_user_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('maximum_score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('passing_percentage_snapshot', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('answers_snapshot', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['participant_user_id'], ['users.id'], name=op.f('fk_questionnaire_attempts_participant_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], name=op.f('fk_questionnaire_attempts_questionnaire_id_questionnaires'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questionnaire_attempts')),
    sa.UniqueConstraint('questionnaire_id', 'participant_user_id', 'attempt_number', name='uq_questionnaire_attempt_number')
    )
    with op.batch_alter_table('questionnaire_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questionnaire_attempts_participant_user_id'), ['participant_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionnaire_attempts_passed'), ['passed'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionnaire_attempts_questionnaire_id'), ['questionnaire_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionnaire_attempts_submitted_at'), ['submitted_at'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('questionnaire_id', sa.String(length=36), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response_type', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], name=op.f('fk_questions_questionnaire_id_questionnaires'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions')),
    sa.UniqueConstraint('questionnaire_id', 'sort_order', name='uq_questionnaire_question_order')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_questionnaire_id'), ['questionnaire_id'], unique=False)

    op.create_table('attempt_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('selected_option_ids', sa.JSON(), nullable=False),
    sa.Column('awarded_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fully_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['questionnaire_attempts.id'], name=op.f('fk_attempt_answers_attempt_id_questionnaire_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_attempt_answers_question_id_questions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempt_answers')),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_attempt_question_answer')
    )
    with op.batch_alter_table('attempt_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_answers_attempt_id'), ['attempt_id'], unique=False)

    op.create_table('question_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score_value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_options_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_options')),
    sa.UniqueConstraint('question_id', 'sort_order', name='uq_question_option_order')
    )
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_options_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_options_question_id'))

    op.drop_table('question_options')
    with op.batch_alter_table('attempt_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_answers_attempt_id'))

    op.drop_table('attempt_answers')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_questionnaire_id'))

    op.drop_table('questions')
    with op.batch_alter_table('questionnaire_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questionnaire_attempts_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_questionnaire_attempts_questionnaire_id'))
        batch_op.drop_index(batch_op.f('ix_questionnaire_attempts_passed'))
        batch_op.drop_index(batch_op.f('ix_questionnaire_attempts_participant_user_id'))

    op.drop_table('questionnaire_attempts')
    with op.batch_alter_table('questionnaires', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questionnaires_is_published'))
        batch_op.drop_index(batch_op.f('ix_questionnaires_course_id'))

    op.drop_table('questionnaires')
    # ### end Alembic commands ###
